### ISSUE TITLE
Self Hosting Guide Link is broken

### ISSUE THREAD

**Issue by the1sword** [New-Horizon-Network/TwitchBot#1]
Upon attempting to access the self hosting guide, the associated webpage is a 404 error from Github Pages.

**Comment by MountainTiger144** [comment]
Thank you for reporting this. We are fixing the pages for the website now and we will try and get back to you when the work has finished.

**Comment by MountainTiger144** [comment]
The link has been fixed. The problem occured because of the renaming of the GitHub Teams which meant that the gh-pages was changed.
